sanitize_report_slug <- function(text) {
  slug <- tolower(gsub("[^A-Za-z0-9]+", "-", text))
  slug <- gsub("(^-+|-+$)", "", slug)
  if (!nzchar(slug)) {
    slug <- "rstudiozhai-report"
  }
  substr(slug, 1L, 80L)
}

qmd_escape <- function(text) {
  text <- paste(as.character(text), collapse = "\n")
  gsub("```", "` ` `", text, fixed = TRUE)
}

build_quarto_report_content <- function(title,
                                        task,
                                        ai_result,
                                        environment_report = NULL) {
  if (!is.character(title) || length(title) != 1L || !nzchar(trimws(title))) {
    stop("title must be a non-empty string", call. = FALSE)
  }
  if (!is.character(task) || length(task) != 1L || !nzchar(trimws(task))) {
    stop("task must be a non-empty string", call. = FALSE)
  }
  if (!is.character(ai_result) || length(ai_result) != 1L || !nzchar(trimws(ai_result))) {
    stop("ai_result must be a non-empty string", call. = FALSE)
  }

  diagnostics <- if (is.null(environment_report)) {
    ""
  } else {
    paste0(
      "\n## Environment Diagnostics\n\n",
      "```text\n",
      qmd_escape(format_environment_report(environment_report)),
      "\n```\n"
    )
  }

  paste0(
    "---\n",
    "title: \"", gsub("\"", "\\\\\"", title), "\"\n",
    "format: html\n",
    "execute:\n",
    "  echo: true\n",
    "  warning: false\n",
    "---\n\n",
    "## Task\n\n",
    qmd_escape(task),
    "\n\n",
    "## AI Workbench Result\n\n",
    "```text\n",
    qmd_escape(ai_result),
    "\n```\n",
    diagnostics,
    "\n## Reproducibility Notes\n\n",
    "- Generated by rstudiozhai.\n",
    "- Review all suggested changes before writing files or executing code.\n"
  )
}

create_quarto_report <- function(task,
                                 ai_result,
                                 output_dir = getwd(),
                                 title = "RStudio Chinese AI Workbench Report",
                                 include_environment = TRUE,
                                 overwrite = FALSE) {
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  }
  if (!dir.exists(output_dir)) {
    stop("output_dir could not be created", call. = FALSE)
  }

  environment_report <- if (isTRUE(include_environment)) {
    collect_environment_report()
  } else {
    NULL
  }

  slug <- sanitize_report_slug(title)
  path <- file.path(output_dir, paste0(slug, ".qmd"))
  if (file.exists(path) && !isTRUE(overwrite)) {
    stamp <- format(Sys.time(), "%Y%m%d-%H%M%S")
    path <- file.path(output_dir, paste0(slug, "-", stamp, ".qmd"))
  }

  content <- build_quarto_report_content(
    title = title,
    task = task,
    ai_result = ai_result,
    environment_report = environment_report
  )
  writeLines(content, path, useBytes = TRUE)

  list(
    ok = TRUE,
    path = normalizePath(path, winslash = "/", mustWork = FALSE),
    title = title,
    rendered = FALSE,
    render_output = ""
  )
}

render_quarto_report <- function(path,
                                 quarto = detect_quarto_info()$path) {
  if (!file.exists(path)) {
    stop("path does not exist", call. = FALSE)
  }
  if (!nzchar(quarto) || !file.exists(quarto)) {
    stop("Quarto CLI is not available", call. = FALSE)
  }

  output <- system2(
    quarto,
    c("render", normalizePath(path, winslash = "/", mustWork = TRUE)),
    stdout = TRUE,
    stderr = TRUE
  )
  status <- attr(output, "status")
  if (is.null(status)) {
    status <- 0L
  }

  list(
    ok = identical(as.integer(status), 0L),
    path = normalizePath(path, winslash = "/", mustWork = FALSE),
    render_output = paste(output, collapse = "\n")
  )
}
